services:

  db:
    image: postgres:13.22-alpine3.22
    environment:
      POSTGRES_PASSWORD: postgres@123#
      POSTGRES_DB: spring_with_liquibase

  app:
    depends_on:
      - db
    build: .
    image: springboot-with-liquibase:1.0.0
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring_with_liquibase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_password: postgres@123#
    ports:
      - 8080:8080